# Generated by Django 4.2.4 on 2025-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("satellites", "0002_satellite_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
