# fly.toml file generated for astrollaneous on 2025-04-11T15:15:36-04:00

app = "astrollaneous"

[experimental]
  auto_rollback = false

[env]
  PORT = "8080"

[build]
  dockerfile = "Dockerfile"

kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443